### ISSUE TITLE
"update" switch to CLI interface

### ISSUE THREAD

**Issue by titaniumbones** [jeveleth/dolley-madison#2]
allow CLI interface to update existing repo set via `git pull origin` rather than initializing a whole new mirror

**Comment by titaniumbones** [comment]
depends on #1

**Comment by jeveleth** [comment]
Can you elaborate on what you're looking for? Do you mean: 

1.  Update the repositories that the user has already forked (i.e., something like a ```git fetch upstream```).
2. Update the original source of repositories to be forked.
3. Something else entirely.

If the answer is number 2, I'm not sure how I'd do that via a ```git pull origin```, as all the repos are stored as text on a page that the code is scraping.

**Comment by titaniumbones** [comment]
I meant (1).  I didn't even look at yr code and still haven't! but if it's possible that would be great.  Yeah, `git fetch upstream` or whatever is pretty much what I'd be looking for.  And might also be helpful to store names of missing repos somewhere.

**Comment by jeveleth** [comment]
Updated repo to sync with upstream master (when possible) based on "update" switch.
