### ISSUE TITLE
fuller instructions for using oauth

### ISSUE THREAD

**Issue by titaniumbones** [jeveleth/dolley-madison#3]
This may be individual ignorance, but I can't get the app to run with a personal access token generated accoding to the [help docs](https://help.github.com/articles/creating-an-access-token-for-command-line-use/) and 

```
GH_OAUTH_KEY='MYKEYHERE' php run.php 
```
in the root directory of the d-m repo.  

could be user error on my end since I don't use oauth normally.

**Comment by titaniumbones** [comment]
also: thanks!

**Comment by jeveleth** [comment]
Do you get any output or an error message? Also, are you passing in the username too?
EDIT: For example, what do you get back when you do the following?
```curl -u username:token https://api.github.com/user```

**Comment by titaniumbones** [comment]
I wasn't at first, but this:

GH_OAUTH+KEY="MYKEY" GH_USERNAME="MYSERNAME" php run.php

did not work in zsh or bash for me either, running in Ubuntu.  However, after hardcoding the key and username I was able to get about 1600 repos mirrored here: 

https://github.com/govtmirror

So, not 100% ideal, but it works for now.

The error message for each organization looked like this:

```
now forking repos for CA-CST-SII organization
Error getting CA-CST-SII: Client error: `GET https://api.github.com/orgs/CA-CST-SII/repos` resulted in a `401 Unauthorized` response:
{
  "message": "Bad credentials",
  "documentation_url": "https://developer.github.com/v3"
}
```


Josh Eveleth writes:

> Do you get any output or an error message? Also, are you passing in the username too?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.


--

**Comment by jeveleth** [comment]
Hrm. Not sure what's going on here. I've tried both by setting the envvars in a .zshrc file and from the CLI (using a completely different user). Not sure why this issue persists for you. It could be the difference between my Mac and your Ubuntu box?
