### ISSUE TITLE
extract comparative data

### ISSUE THREAD

**Issue by titaniumbones** [jeveleth/dolley-madison#4]
If the script recorded changes from a baseline date (say, today), we oculd keep track of whether repositories are disappearing.  E.g., it oculd write repo name, URL, agency to a csv file.

**Comment by jeveleth** [comment]
Good idea. Lemme see what I can do.

**Comment by titaniumbones** [comment]
If we could even get all the repo URL's printed to a textfile or a csv that would be pretty helpful I think..

**Comment by jeveleth** [comment]
Cool. I'll poke at it on the plane.

**Comment by jeveleth** [comment]
I've addressed this (I hope) in the latest merge: https://github.com/jeveleth/dolley-madison/commit/b387f6aef9dbcdb81cfa34c4d3bcfe4b208981ce
